---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: message-service
  name: message-service
  namespace: discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: message-service
  name: message-service:view
  namespace: discovery
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: message-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader
  namespace: discovery
rules:
  - apiGroups: [“”, “extensions”, “apps”]
    resources: [“configmaps”, “pods”, “services”, “endpoints”, “secrets”]
    verbs: [“get”, “list”, “watch”]
