apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: billboard-client
  name: billboard-client
  namespace: discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: billboard-client
  name: billboard-client:view
  namespace: discovery
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: billboard-client
